import type { Metadata } from "next";
import Sidebar from "@/components/organisms/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex bg-[#F7F6EF]">
          <Sidebar />
          {children}
        </div>
      </body>
    </html >
  );
}
